name: 'Build Flake and push to attic'
description: 'Build a Flakes nixosConfigurations and packages, then push them to the attic instance'
author: "Svenum"
inputs:
  attic_url:
    description: "URL to your attic endpoint"
    required: true
  attic_cache:
    description: "Name form the cache to use"
    required: true
  attic_token:
    description: "Token to authenticate on the attic server"
    required: true
  build_systems:
    description: "If enabled nixoxConfigurations are build and pushed"
    default: true
    required: true
  build_packages:
    description: "If enabled packages are build and pushed"
    default: true
    required: true
  dont_fail:
    description: "If enabled, packages that fail in their build will not"
    default: false
    required: false
  little_space:
    description: "If enabled, all build get deleted bevor the next starts, this saves diskspace"
    default: true
    required: false
  no_keep_attic_conf:
    description: "Deletes the Attic conf before running the main script (usefull for persistent runners)"
    default: false
    required: false
  flake_path:
    description: "If your flake path is something other than the default, you can set it with this var"
    default: "."
    required: false
  only_build_sytems:
    description: "If you want to only build specific systems, you can set them here (comma seperated string of hostnames)"
    required: false
  max_jobs:
    description: "Set the maximum number of jobs to run at the same time"
    required: false
  log_level:
    description: "Set the Log Level for the script (can be DEBUG, INFO, WARNING, ERROR)"
    required: false
    default: "INFO"
  json_logging:
    description: "If enabled, the log will be in json format"
    required: false
    default: "false"
runs:
  using: 'composite'
  steps:
    - run: nix-shell ${GITHUB_ACTION_PATH}/shell.nix --run "bun run ${GITHUB_ACTION_PATH}"
      shell: bash
      env:
        BUILD_SYSTEMS: ${{ inputs.build_systems }}
        BUILD_PACKAGES: ${{ inputs.build_packages }}
        ATTIC_CACHE_URL: ${{ inputs.attic_url }}
        ATTIC_CACHE_NAME: ${{ inputs.attic_cache }}
        ATTIC_CACHE_TOKEN: ${{ inputs.attic_token }}
        FLAKE_PATH: ${{ github.flake_apth }}
        INSTALL_DEPS: true
        LITTLE_SPACE: ${{ inputs.little_space }}
        DONT_FAIL: ${{ inputs.dont_fail }}
        NO_KEEP_ATTIC_CONF: ${{ inputs.no_keep_attic_conf}}
        ONLY_BUILD_SYSTEMS: ${{ inputs.build_systems }}
        MAX_JOBS: ${{ inputs.max_jobs }}
        LOG_LEVEL: ${{ inputs.log_level }}
        JSON_LOGGING: ${{ inputs.json_logging }}